name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Lint / Typecheck / Test / Audit
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          # Ensure CI tools are available
          pip install ruff mypy pytest pip-audit

      - name: Lint with ruff
        run: |
          echo "Running ruff..."
          ruff check .

      - name: Type-check with mypy
        run: |
          echo "Running mypy..."
          mypy .

      - name: Run tests with pytest
        run: |
          echo "Running pytest..."
          pytest -q

      - name: Security audit (pip-audit)
        run: |
          echo "Running pip-audit..."
          pip-audit --progress never
